services:
  - type: web
    name: spotime-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: spotime-db
          property: connectionString
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://spotime.vercel.app

databases:
  - name: spotime-db
    plan: free
